image: python:3.8

stages:
  - check
  - test
  - deploy

pylint:
  stage: check
  before_script:
    - pip3 install -r requirements.txt
    - pip3 install flake8
  script:
    - flake8 meetupselector/

test:
  stage: test
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python manage.py test
