# Generated by Django 3.1.2 on 2020-10-10 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicproposal',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='topicproposal',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
