# Generated by Django 3.1.2 on 2020-10-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votesystem', '0003_auto_20201021_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedPonent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('proposed_meetup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votesystem.proposedmeetup')),
            ],
            options={
                'verbose_name': 'Ponente',
                'verbose_name_plural': 'Ponentes',
            },
        ),
    ]
