# Generated by Django 3.1.2 on 2020-10-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votesystem', '0004_proposedponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposedponent',
            options={},
        ),
    ]
