# Generated by Django 3.1.2 on 2020-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votesystem', '0005_auto_20201027_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedmeetup',
            name='month',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=11),
        ),
    ]
