# Generated by Django 3.1.2 on 2020-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagecontent',
            name='content',
            field=models.TextField(default='Python Alicante', help_text='Place here the content for your landing page'),
        ),
    ]
