# Generated by Django 3.1.2 on 2020-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20201024_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', help_text='Title', max_length=250),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='Create the content in the admin page', help_text='Place here the content for your landing page'),
        ),
    ]
