# Generated by Django 3.1.2 on 2020-10-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20201024_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='Your title goes here', help_text='Your title goes here', max_length=250),
        ),
    ]
