# Generated by Django 3.1.2 on 2020-10-27 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20201024_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='', help_text='Place here the content for your landing page'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='', help_text='Your title goes here', max_length=250),
        ),
    ]
