# Generated by Django 3.1.2 on 2020-10-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20201024_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', help_text='Lirst name of collaborator', max_length=250)),
                ('last_name', models.CharField(default='', help_text='Last name of collaborator', max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(default='', help_text='Collaborator nationality', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='', help_text='Place here the content for your landing page'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='', help_text='Your title goes here', max_length=250),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Social network link', max_length=250)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.collaborator')),
            ],
        ),
    ]
