# Generated by Django 3.1.2 on 2020-10-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_auto_20201029_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network', to='landingpage.collaborator'),
        ),
    ]
