# Generated by Django 3.1.2 on 2020-10-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_auto_20201029_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='network',
            field=models.CharField(default='', help_text='Social network name', max_length=250),
        ),
    ]
