# Generated by Django 3.1.2 on 2020-10-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_socialnetwork_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='profile',
            field=models.CharField(default='', help_text='Collaborator profile', max_length=250),
        ),
    ]
