# Generated by Django 3.1.2 on 2020-10-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_auto_20201030_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
