# Generated by Django 3.1.2 on 2020-10-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_auto_20201027_2228'),
        ('landingpage', '0011_collaborator_avatar'),
    ]

    operations = [
    ]
