# Generated by Django 3.1.2 on 2020-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_merge_20201030_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Last name of collaborator', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='Collaborator nationality', max_length=250, null=True),
        ),
    ]
